version: '3'
services:
  web:
    build:
      context: ./Docker/web
      args:
        REACT_APP_API_URL: http://pwd10-0-134-3-3100.host2.labs.play-with-docker.com
        REACT_APP_ADMIN_URL: http://pwd10-0-134-3-8080.host2.labs.play-with-docker.com
    image: jsalgado/appdemoinfra_web:meetup
    labels:
      com.app-demo-infra.web.description: "Voting app"
    ports:
      - "80:5000"
    deploy:
      replicas: 2
    command: [serve, -s, build]
  admin:
    build:
      context: ./Docker/admin
      args:
        REACT_APP_API_URL: http://pwd10-0-134-3-3100.host2.labs.play-with-docker.com
    image: jsalgado/appdemoinfra_admin:meetup
    labels:
      com.app-demo-infra.admin.description: "Result display app"
    ports:
      - "8080:5000"
    deploy:
      replicas: 2
    command: [serve, -s, build]
  api:
    build: ./Docker/api
    image: jsalgado/appdemoinfra_api:meetup
    labels:
      com.app-demo-infra.web.description: "Voting API"
    ports:
      - "3100:3100"
    deploy:
      replicas: 2
    depends_on:
      - db
    networks:
      - backend
    command: [npm, start]
  db:
    image: mongo
    networks:
      - backend

networks:
  backend:
